---
title: "02-justeduc"
author: "Equipo EDUMER"
date: '2022-06-27'
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
---

```{r}
pacman::p_load(haven, dplyr, summarytools, sjmisc, car, sjlabelled, sjPlot, lme4, stargazer, corrplot, ltm, texreg, ordinal, MASS)
load("input/data/original/base_estudiantes.RData")
load("input/data/original/base_apoderados.RData")
```

```{r}
data_est <- base_estudiantes %>% dplyr::select(idalumno,
                                               sexo,
                                               codigoCurso,
                                               mrbd,
                                               cod_depe2, #dependencia administrativa
                                               cod_grupo, #categorizacion socioeconomica
                                               simce_lect=prom_lect8b_rbd, #Promedio lectura escuela
                                               simce_mate=prom_mate8b_rbd, # Promedio matematica escuela
                                               inteligencia_esc=est_p6_1, # inteligencia escolar
                                               esfuerzo_esc=est_p6_2, # esfuerzo escolar
                                               esfuerzo_soc=est_p38_2, #esfuerzo social
                                               merito_soc=est_p38_3, #merito social
                                               inteligencia_soc=est_p38_4, #inteligencia social
                                               just_pension=est_p39_1, #justicia pension
                                               just_educ=est_p39_2, # justicia educacion
                                               just_salud=est_p39_3, # justicia salud
                                               redistribucion=est_p39_4, # redistribucion
                                               libros=est_p3, # cantidad de libros
                                               pc=est_p4_1, # tiene pc
                                               tablet=est_p4_2, # tiene tablet
                                               celular=est_p4_3 # tiene celular
                                               ) %>% as.data.frame(.)

data_apod <- base_apoderados %>% dplyr::select(idalumno,
                                               educacion=educ_max, # nivel educacional mas alto
                                               internet=apod_p9 # conexion a internet en la casa
                                               ) %>% as.data.frame(.)

data_apod <- data_apod %>%  set_na(internet, na = c(0,99), drop.levels = FALSE, as.tag = FALSE) # recode missings de doble marca (99) y vacío (0) a NA
```

## merge bases
```{r}
data <- left_join(data_est, data_apod, by="idalumno")
rm(base_apoderados, base_estudiantes, data_est, data_apod)
```

```{r}
#Educacion
data$educacion_rec <- ifelse(is.na(data$educacion), "Ns/Nr", data$educacion)
data <- data %>% rowwise() %>%  mutate(educacion_rec = case_when(educacion_rec==1~"Ed Basica",
                                                 educacion_rec==2~"Ed Basica",
                                                 educacion_rec==3~"Ed Basica",
                                                 educacion_rec==4~"Ed Media",
                                                 educacion_rec==5~"Ed Media",
                                                 educacion_rec==6~"Ed Tecnica",
                                                 educacion_rec==7~"Ed Tecnica",
                                                 educacion_rec==8~"Universidad o posgrado",
                                                 educacion_rec==9~"Universidad o posgrado",
                                                 educacion_rec==10~"Universidad o posgrado",
                                                 educacion_rec=="Ns/Nr"~"Ns/Nr"
                                                 ))
data$educacion_rec <- factor(data$educacion_rec, levels = c("Ed Basica", "Ed Media", "Ed Tecnica", "Universidad o posgrado", "Ns/Nr"))

# Internet
data$internet <- factor(data$internet, labels = c("Si", "No"))
data$internet_rec <- ifelse(is.na(data$internet), "Ns/Nr", data$internet)

# libros
data$libros_rec <- as.numeric(data$libros)
data <- data %>% rowwise() %>% mutate(libros_rec = case_when(libros_rec==1 ~ "Menos de 25",
                                                             libros_rec==2 ~ "Menos de 25",
                                                             libros_rec==3 ~ "Más de 25",
                                                             libros_rec==4 ~ "Más de 25",
                                                             libros_rec==5 ~ "Más de 25"))
data$libros_rec <- factor(data$libros_rec, levels = c("Menos de 25", "Más de 25"))
```

```{r}
data <- data %>% rowwise() %>% mutate(prom_simce = mean(simce_lect,simce_mate))
summary(data$prom_simce)
data$simce <- ntile(data$prom_simce,3)
table(data$simce)
data$simce <- factor(data$simce, labels = c("Bajo", "Medio", "Alto"))
```

```{r}
# Acceso a tecnologia
data$pc <- as.numeric(data$pc)
data$tablet <- as.numeric(data$tablet)
data$celular <- as.numeric(data$celular)

corrplot.mixed(cor(dplyr::select(data, pc, tablet, celular),
                   method = "spearman",
                   use = "complete.obs"))
```

```{r}
ltm::cronbach.alpha(data  %>%
  dplyr::select(pc, tablet, celular), na.rm=TRUE)
```

```{r}
data <- data %>% rowwise() %>% dplyr::mutate(acc_tec = sum(pc, tablet, celular, na.rm = T))
summary(data$acc_tec)
```

```{r}
# Variables meritocracia
data$inteligencia_esc <- as.numeric(data$inteligencia_esc)
data$esfuerzo_esc <- as.numeric(data$esfuerzo_esc)
data$esfuerzo_soc <- as.numeric(data$esfuerzo_soc)
data$merito_soc <- as.numeric(data$merito_soc)
data$inteligencia_soc <- as.numeric(data$inteligencia_soc)
data$just_pension <- as.numeric(data$just_pension)
data$just_salud <- as.numeric(data$just_salud)
data$just_educ <- as.numeric(data$just_educ)
data$redistribucion <- as.numeric(data$redistribucion)
```

```{r}
data_rec <- data %>% dplyr::select(-educacion, -internet, -simce_lect, -simce_mate, -libros, -pc, -tablet, -celular)
```

# Modelos de regresión logística ordenada (ordinal logit) (CLMM del paquete ordinal - Cumulative link mixed models)

## Es justo que las personas de ingresos altos puedan optar a mejor educacion

```{r}
data_educ <- data_rec %>% dplyr::select(-just_pension, -just_salud, -redistribucion)
data_educ <- na.omit(data_educ)
```

```{r}
data_educ$just_educ_fact <- as_factor(data_educ$just_educ)
reg0_educ <- clmm(just_educ_fact ~ 1 + (1 | mrbd), data = data_educ)
reg1_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + (1 | mrbd), data=data_educ)
reg2_educ <- clmm(just_educ_fact ~ 1 + merito_soc + (1 | mrbd), data=data_educ)
reg3_educ <- clmm(just_educ_fact ~ 1 + inteligencia_soc + (1 | mrbd), data=data_educ)
reg4_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_esc + (1 | mrbd), data=data_educ)
reg5_educ <- clmm(just_educ_fact ~ 1 + inteligencia_esc + (1 | mrbd), data=data_educ)
reg6_educ <- clmm(just_educ_fact ~ 1 + educacion_rec + (1 | mrbd), data=data_educ)
reg7_educ <- clmm(just_educ_fact ~ 1 + libros_rec + (1 | mrbd), data=data_educ)
reg8_educ <- clmm(just_educ_fact ~ 1 + acc_tec + (1 | mrbd), data=data_educ)
reg9_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 | mrbd), data=data_educ)
```

```{r results='asis'}
htmlreg(list(reg0_educ, reg1_educ, reg2_educ, reg3_educ, reg4_educ, reg5_educ, reg6_educ, reg7_educ, reg8_educ, reg9_educ), 
        custom.model.names = c("Nulo",
                               "Modelo 1",
                               "Modelo 2",
                               "Modelo 3",
                               "Modelo 4",
                               "Modelo 5",
                               "Modelo 6",
                               "Modelo 7",
                               "Modelo 8",
                               "Modelo 9"), 
        custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05", 
        omit.coef = "(internet_rec)",
        custom.coef.names = c("Muy desacuerdo|Desacuerdo",
                              "Desacuerdo|De acuerdo",
                              "De acuerdo|Muy de acuerdo",
                              "Esfuerzo social", 
                              "Merito social", 
                              "Inteligencia social", 
                              "Esfuerzo escolar", 
                              "Inteligencia escolar", 
                              "Ed media <br> <i>(Ref. Ed Basica)</i>", 
                              "Ed tecnica", "Universidad o posgrado", 
                              "Ns/Nr", 
                              "Más de 25 libros <br> <i>(Ref. Menos de 25)</i>", 
                              "Acceso a tecnología", 
                              "Part. subv <br> <i>(Ref. Municipal)</i>", 
                              "Part. priv", 
                              "SES Medio bajo <br> <i>(Ref. Bajo)</i>", 
                              "SES Medio", 
                              "SES Medio alto", 
                              "SES Alto", 
                              "Simce_Medio <i>(Ref. Bajo)</i>", 
                              "Simce_alto"))
```

### Interacciones

*meritocracia x ses familiar (educacion)*

```{r}
reg10_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec*esfuerzo_soc + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + educacion_rec | mrbd), data=data_educ)
reg11_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec*merito_soc + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + educacion_rec | mrbd), data=data_educ)
reg12_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec*inteligencia_soc + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + educacion_rec | mrbd), data=data_educ)
reg13_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec*esfuerzo_esc + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + educacion_rec | mrbd), data=data_educ)
reg14_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec*inteligencia_esc + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + educacion_rec | mrbd), data=data_educ)
```

```{r results='asis'}
htmlreg(list(reg9_educ, reg10_educ, reg11_educ, reg12_educ, reg13_educ, reg14_educ))
```

*meritocracia x ses familiar (libros)*

```{r}
reg15_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec*esfuerzo_soc + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + libros_rec | mrbd), data=data_educ)
reg16_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec*merito_soc + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + libros_rec | mrbd), data=data_educ)
reg17_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec*inteligencia_soc + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + libros_rec | mrbd), data=data_educ)
reg18_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec*esfuerzo_esc + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + libros_rec | mrbd), data=data_educ)
reg19_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec*inteligencia_esc + acc_tec + cod_depe2 + cod_grupo + simce + internet_rec + (1 + libros_rec | mrbd), data=data_educ)
```

```{r results='asis'}
htmlreg(list(reg9_educ, reg15_educ, reg16_educ, reg17_educ, reg18_educ, reg19_educ))
```

*meritocracia x ses escuela*

```{r}
reg20_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo*esfuerzo_soc + simce + internet_rec + (1 + cod_grupo | mrbd), data=data_educ)
reg21_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo*merito_soc + simce + internet_rec + (1 + cod_grupo | mrbd), data=data_educ)
reg22_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo*inteligencia_soc + simce + internet_rec + (1 + cod_grupo | mrbd), data=data_educ)
reg23_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo*esfuerzo_esc + simce + internet_rec + (1 + cod_grupo | mrbd), data=data_educ)
reg24_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo*inteligencia_esc + simce + internet_rec + (1 + cod_grupo | mrbd), data=data_educ)
```

```{r results='asis'}
htmlreg(list(reg9_educ, reg20_educ, reg21_educ, reg22_educ, reg23_educ, reg24_educ))
```

*meritocracia x simce*

```{r}
reg25_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce*esfuerzo_soc + internet_rec + (1 + simce | mrbd), data=data_educ)
reg26_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce*merito_soc + internet_rec + (1 + simce | mrbd), data=data_educ)
reg27_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce*inteligencia_soc + internet_rec + (1 + simce | mrbd), data=data_educ)
reg28_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce*esfuerzo_esc + internet_rec + (1 + simce | mrbd), data=data_educ)
reg29_educ <- clmm(just_educ_fact ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros_rec + acc_tec + cod_depe2 + cod_grupo + simce*inteligencia_esc + internet_rec + (1 + simce | mrbd), data=data_educ)
```

```{r results='asis'}
htmlreg(list(reg9_educ, reg25_educ, reg26_educ, reg27_educ, reg28_educ, reg29_educ))
```