---
title: "analisis-multinivel"
author: "Equipo EDUMER"
date: '2022-06-13'
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
---

```{r}
pacman::p_load(haven, dplyr, summarytools, sjmisc, car, sjlabelled, lme4, stargazer, corrplot, ltm, texreg)
load("input/data/original/base_estudiantes.RData")
load("input/data/original/base_apoderados.RData")
```

```{r}
data_est <- base_estudiantes %>% dplyr::select(idalumno,
                                               sexo,
                                               codigoCurso,
                                               mrbd,
                                               cod_depe2, #dependencia administrativa
                                               cod_grupo, #categorizacion socioeconomica
                                               simce_lect=prom_lect8b_rbd, #Promedio lectura escuela
                                               simce_mate=prom_mate8b_rbd, # Promedio matematica escuela
                                               inteligencia_esc=est_p6_1, # inteligencia escolar
                                               esfuerzo_esc=est_p6_2, # esfuerzo escolar
                                               esfuerzo_soc=est_p38_2, #esfuerzo social
                                               merito_soc=est_p38_3, #merito social
                                               inteligencia_soc=est_p38_4, #inteligencia social
                                               just_pension=est_p39_1, #justicia pension
                                               just_educ=est_p39_2, # justicia educacion
                                               just_salud=est_p39_3, # justicia salud
                                               redistribucion=est_p39_4, # redistribucion
                                               libros=est_p3, # cantidad de libros
                                               pc=est_p4_1, # tiene pc
                                               tablet=est_p4_2, # tiene tablet
                                               celular=est_p4_3 # tiene celular
                                               ) %>% as.data.frame(.)

data_apod <- base_apoderados %>% dplyr::select(idalumno,
                                               educacion=educ_max, # nivel educacional mas alto
                                               internet=apod_p9 # conexion a internet en la casa
                                               ) %>% as.data.frame(.)

data_apod <- data_apod %>%  set_na(internet, na = c(0,99), drop.levels = FALSE, as.tag = FALSE) # recode missings de doble marca (99) y vacío (0) a NA
```

## merge bases
```{r}
data <- left_join(data_est, data_apod, by="idalumno")
rm(base_apoderados, base_estudiantes, data_est, data_apod)
```

```{r}
data$educacion_rec <- ifelse(is.na(data$educacion), "Ns/Nr", data$educacion)
data <- data %>% rowwise() %>%  mutate(educacion_rec = case_when(educacion_rec==1~"Ed Basica",
                                                 educacion_rec==2~"Ed Basica",
                                                 educacion_rec==3~"Ed Basica",
                                                 educacion_rec==4~"Ed Media",
                                                 educacion_rec==5~"Ed Media",
                                                 educacion_rec==6~"Ed Tecnica",
                                                 educacion_rec==7~"Ed Tecnica",
                                                 educacion_rec==8~"Universidad o posgrado",
                                                 educacion_rec==9~"Universidad o posgrado",
                                                 educacion_rec==10~"Universidad o posgrado",
                                                 educacion_rec=="Ns/Nr"~"Ns/Nr"
                                                 ))
data$educacion_rec <- factor(data$educacion_rec, levels = c("Ed Basica", "Ed Media", "Ed Tecnica", "Universidad o posgrado", "Ns/Nr"))

data$internet <- factor(data$internet, labels = c("Si", "No"))
data$internet_rec <- ifelse(is.na(data$internet), "Ns/Nr", data$internet)
```

```{r}
data$inteligencia_esc <- as.numeric(data$inteligencia_esc)
data$esfuerzo_esc <- as.numeric(data$esfuerzo_esc)
data$esfuerzo_soc <- as.numeric(data$esfuerzo_soc)
data$merito_soc <- as.numeric(data$merito_soc)
data$inteligencia_soc <- as.numeric(data$inteligencia_soc)
data$just_pension <- as.numeric(data$just_pension)
data$just_salud <- as.numeric(data$just_salud)
data$just_educ <- as.numeric(data$just_educ)
data$redistribucion <- as.numeric(data$redistribucion)

data <- data %>% rowwise() %>% mutate(prom_simce = mean(simce_lect,simce_mate))
summary(data$prom_simce)
data$simce <- ntile(data$prom_simce,3)
table(data$simce)
data$simce <- factor(data$simce, labels = c("Bajo", "Medio", "Alto"))
```

```{r}
data_rec <- data %>% dplyr::select(-educacion, -internet, -simce_lect, -simce_mate)
```

# Es justo que las personas de ingresos altos puedan optar a mejores pensiones

```{r}
data_pension <- data_rec %>% dplyr::select(-just_educ, -just_salud, -redistribucion)
data_pension <- na.omit(data_pension)
```


```{r}
reg1_pension <- lmer(just_pension ~ 1 + esfuerzo_soc + (1 | mrbd), data=data_pension)
reg2_pension <- lmer(just_pension ~ 1 + merito_soc + (1 | mrbd), data=data_pension)
reg3_pension <- lmer(just_pension ~ 1 + inteligencia_soc + (1 | mrbd), data=data_pension)
reg4_pension <- lmer(just_pension ~ 1 + esfuerzo_esc + (1 | mrbd), data=data_pension)
reg5_pension <- lmer(just_pension ~ 1 + inteligencia_esc + (1 | mrbd), data=data_pension)
reg6_pension <- lmer(just_pension ~ 1 + educacion_rec + (1 | mrbd), data=data_pension)
reg7_pension <- lmer(just_pension ~ 1 + libros + (1 | mrbd), data=data_pension)
reg8_pension <- lmer(just_pension ~ 1 + pc + tablet + celular + internet_rec + (1 | mrbd), data=data_pension)
reg9_pension <- lmer(just_pension ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros + pc + tablet + celular + internet_rec + cod_depe2 + cod_grupo + simce + (1 | mrbd), data=data_pension)
```


```{r results='asis'}
htmlreg(list(reg1_pension, reg2_pension, reg3_pension, reg4_pension, reg5_pension, reg6_pension, reg7_pension, reg8_pension, reg9_pension), custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"), custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05", custom.coef.names = c("Intercepto", "Esfuerzo social", "Merito social", "Inteligencia social", "Esfuerzo escolar", "Inteligencia escolar", "Ed media <br> <i>(Ref. Ed Basica)</i>", "Ed tecnica", "Universidad o posgrado", "Ns/Nr", "10 a 25 libros <br> <i>(Ref. Menos de 10)</i>", "26 a 100 libros", "101 a 200 libros", "Más de 200 libros", "Un pc <br> <i>(Ref. Ninguno)</i>", "Dos pc", "Tres o más pc", "Una tablet <br> <i>(Ref. Ninguno)</i>", "Dos tablet", "Tres o mas tablet", "Un celular <br> <i>(Ref. Ninguno)</i>", "Dos celular", "Tres o más celular", "No internet <br> <i>(Ref. Si)</i>", "Ns/Nr internet", "Part. subv <br> <i>(Ref. Municipal)</i>", "Part. priv", "SES Medio bajo <br> <i>(Ref. Bajo)</i>", "SES Medio", "SES Medio alto", "SES Alto", "Simce_Medio <i>(Ref. Bajo)</i>", "Simce_alto"))
```

# Es justo que las personas de ingresos altos puedan optar a mejor educacion

```{r}
data_educ <- data_rec %>% dplyr::select(-just_pension, -just_salud, -redistribucion)
data_educ <- na.omit(data_educ)
```


```{r}
reg1_educ <- lmer(just_educ ~ 1 + esfuerzo_soc + (1 | mrbd), data=data_educ)
reg2_educ <- lmer(just_educ ~ 1 + merito_soc + (1 | mrbd), data=data_educ)
reg3_educ <- lmer(just_educ ~ 1 + inteligencia_soc + (1 | mrbd), data=data_educ)
reg4_educ <- lmer(just_educ ~ 1 + esfuerzo_esc + (1 | mrbd), data=data_educ)
reg5_educ <- lmer(just_educ ~ 1 + inteligencia_esc + (1 | mrbd), data=data_educ)
reg6_educ <- lmer(just_educ ~ 1 + educacion_rec + (1 | mrbd), data=data_educ)
reg7_educ <- lmer(just_educ ~ 1 + libros + (1 | mrbd), data=data_educ)
reg8_educ <- lmer(just_educ ~ 1 + pc + tablet + celular + internet_rec + (1 | mrbd), data=data_educ)
reg9_educ <- lmer(just_educ ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros + pc + tablet + celular + internet_rec + cod_depe2 + cod_grupo + simce + (1 | mrbd), data=data_educ)
```


```{r results='asis'}
htmlreg(list(reg1_educ, reg2_educ, reg3_educ, reg4_educ, reg5_educ, reg6_educ, reg7_educ, reg8_educ, reg9_educ), custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"), custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05", custom.coef.names = c("Intercepto", "Esfuerzo social", "Merito social", "Inteligencia social", "Esfuerzo escolar", "Inteligencia escolar", "Ed media <br> <i>(Ref. Ed Basica)</i>", "Ed tecnica", "Universidad o posgrado", "Ns/Nr", "10 a 25 libros <br> <i>(Ref. Menos de 10)</i>", "26 a 100 libros", "101 a 200 libros", "Más de 200 libros", "Un pc <br> <i>(Ref. Ninguno)</i>", "Dos pc", "Tres o más pc", "Una tablet <br> <i>(Ref. Ninguno)</i>", "Dos tablet", "Tres o mas tablet", "Un celular <br> <i>(Ref. Ninguno)</i>", "Dos celular", "Tres o más celular", "No internet <br> <i>(Ref. Si)</i>", "Ns/Nr internet", "Part. subv <br> <i>(Ref. Municipal)</i>", "Part. priv", "SES Medio bajo <br> <i>(Ref. Bajo)</i>", "SES Medio", "SES Medio alto", "SES Alto", "Simce_Medio <i>(Ref. Bajo)</i>", "Simce_alto"))
```

# Es justo que las personas de ingresos altos puedan optar a mejor salud

```{r}
data_salud <- data_rec %>% dplyr::select(-just_pension, -just_educ, -redistribucion)
data_salud <- na.omit(data_salud)
```


```{r}
reg1_salud <- lmer(just_salud ~ 1 + esfuerzo_soc + (1 | mrbd), data=data_salud)
reg2_salud <- lmer(just_salud ~ 1 + merito_soc + (1 | mrbd), data=data_salud)
reg3_salud <- lmer(just_salud ~ 1 + inteligencia_soc + (1 | mrbd), data=data_salud)
reg4_salud <- lmer(just_salud ~ 1 + esfuerzo_esc + (1 | mrbd), data=data_salud)
reg5_salud <- lmer(just_salud ~ 1 + inteligencia_esc + (1 | mrbd), data=data_salud)
reg6_salud <- lmer(just_salud ~ 1 + educacion_rec + (1 | mrbd), data=data_salud)
reg7_salud <- lmer(just_salud ~ 1 + libros + (1 | mrbd), data=data_salud)
reg8_salud <- lmer(just_salud ~ 1 + pc + tablet + celular + internet_rec + (1 | mrbd), data=data_salud)
reg9_salud <- lmer(just_salud ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros + pc + tablet + celular + internet_rec + cod_depe2 + cod_grupo + simce + (1 | mrbd), data=data_salud)
```


```{r results='asis'}
htmlreg(list(reg1_salud, reg2_salud, reg3_salud, reg4_salud, reg5_salud, reg6_salud, reg7_salud, reg8_salud, reg9_salud), custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"), custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05", custom.coef.names = c("Intercepto", "Esfuerzo social", "Merito social", "Inteligencia social", "Esfuerzo escolar", "Inteligencia escolar", "Ed media <br> <i>(Ref. Ed Basica)</i>", "Ed tecnica", "Universidad o posgrado", "Ns/Nr", "10 a 25 libros <br> <i>(Ref. Menos de 10)</i>", "26 a 100 libros", "101 a 200 libros", "Más de 200 libros", "Un pc <br> <i>(Ref. Ninguno)</i>", "Dos pc", "Tres o más pc", "Una tablet <br> <i>(Ref. Ninguno)</i>", "Dos tablet", "Tres o mas tablet", "Un celular <br> <i>(Ref. Ninguno)</i>", "Dos celular", "Tres o más celular", "No internet <br> <i>(Ref. Si)</i>", "Ns/Nr internet", "Part. subv <br> <i>(Ref. Municipal)</i>", "Part. priv", "SES Medio bajo <br> <i>(Ref. Bajo)</i>", "SES Medio", "SES Medio alto", "SES Alto", "Simce_Medio <i>(Ref. Bajo)</i>", "Simce_alto"))
```

# El gobierno deberia hacer algo para disminuir las brechas de ingresos

```{r}
data_redis <- data_rec %>% dplyr::select(-just_pension, -just_educ, -just_salud)
data_redis <- na.omit(data_redis)
```


```{r}
reg1_redis <- lmer(redistribucion ~ 1 + esfuerzo_soc + (1 | mrbd), data=data_redis)
reg2_redis <- lmer(redistribucion ~ 1 + merito_soc + (1 | mrbd), data=data_redis)
reg3_redis <- lmer(redistribucion ~ 1 + inteligencia_soc + (1 | mrbd), data=data_redis)
reg4_redis <- lmer(redistribucion ~ 1 + esfuerzo_esc + (1 | mrbd), data=data_redis)
reg5_redis <- lmer(redistribucion ~ 1 + inteligencia_esc + (1 | mrbd), data=data_redis)
reg6_redis <- lmer(redistribucion ~ 1 + educacion_rec + (1 | mrbd), data=data_redis)
reg7_redis <- lmer(redistribucion ~ 1 + libros + (1 | mrbd), data=data_redis)
reg8_redis <- lmer(redistribucion ~ 1 + pc + tablet + celular + internet_rec + (1 | mrbd), data=data_redis)
reg9_redis <- lmer(redistribucion ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros + pc + tablet + celular + internet_rec + cod_depe2 + cod_grupo + simce + (1 | mrbd), data=data_redis)
```


```{r results='asis'}
htmlreg(list(reg1_redis, reg2_redis, reg3_redis, reg4_redis, reg5_redis, reg6_redis, reg7_redis, reg8_redis, reg9_redis), custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"), custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05", custom.coef.names = c("Intercepto", "Esfuerzo social", "Merito social", "Inteligencia social", "Esfuerzo escolar", "Inteligencia escolar", "Ed media <br> <i>(Ref. Ed Basica)</i>", "Ed tecnica", "Universidad o posgrado", "Ns/Nr", "10 a 25 libros <br> <i>(Ref. Menos de 10)</i>", "26 a 100 libros", "101 a 200 libros", "Más de 200 libros", "Un pc <br> <i>(Ref. Ninguno)</i>", "Dos pc", "Tres o más pc", "Una tablet <br> <i>(Ref. Ninguno)</i>", "Dos tablet", "Tres o mas tablet", "Un celular <br> <i>(Ref. Ninguno)</i>", "Dos celular", "Tres o más celular", "No internet <br> <i>(Ref. Si)</i>", "Ns/Nr internet", "Part. subv <br> <i>(Ref. Municipal)</i>", "Part. priv", "SES Medio bajo <br> <i>(Ref. Bajo)</i>", "SES Medio", "SES Medio alto", "SES Alto", "Simce_Medio <i>(Ref. Bajo)</i>", "Simce_alto"))
```


# Probar indice variables acceso a bienestar social

```{r}
data_bienestar <- na.omit(data_rec)

corrplot.mixed(cor(dplyr::select(data_bienestar, just_educ, just_salud, just_pension),
                   method = "spearman",
                   use = "complete.obs"))
```


```{r}
ltm::cronbach.alpha(data_bienestar  %>%
  dplyr::select(just_educ, just_salud, just_pension), na.rm=TRUE)
```

```{r}
data_bienestar <- data_bienestar %>% rowwise() %>% dplyr::mutate(bienestar = mean(just_educ, just_salud, just_pension, na.rm = T))
```

```{r}
reg1_bienestar <- lmer(bienestar ~ 1 + esfuerzo_soc + (1 | mrbd), data=data_bienestar)
reg2_bienestar <- lmer(bienestar ~ 1 + merito_soc + (1 | mrbd), data=data_bienestar)
reg3_bienestar <- lmer(bienestar ~ 1 + inteligencia_soc + (1 | mrbd), data=data_bienestar)
reg4_bienestar <- lmer(bienestar ~ 1 + esfuerzo_esc + (1 | mrbd), data=data_bienestar)
reg5_bienestar <- lmer(bienestar ~ 1 + inteligencia_esc + (1 | mrbd), data=data_bienestar)
reg6_bienestar <- lmer(bienestar ~ 1 + educacion_rec + (1 | mrbd), data=data_bienestar)
reg7_bienestar <- lmer(bienestar ~ 1 + libros + (1 | mrbd), data=data_bienestar)
reg8_bienestar <- lmer(bienestar ~ 1 + pc + tablet + celular + internet_rec + (1 | mrbd), data=data_bienestar)
reg9_bienestar <- lmer(bienestar ~ 1 + esfuerzo_soc + merito_soc + inteligencia_soc + esfuerzo_esc + inteligencia_esc + educacion_rec + libros + pc + tablet + celular + internet_rec + cod_depe2 + cod_grupo + simce + (1 | mrbd), data=data_bienestar)
```


```{r results='asis'}
htmlreg(list(reg1_bienestar, reg2_bienestar, reg3_bienestar, reg4_bienestar, reg5_bienestar, reg6_bienestar, reg7_bienestar, reg8_bienestar, reg9_bienestar), custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"), custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05", custom.coef.names = c("Intercepto", "Esfuerzo social", "Merito social", "Inteligencia social", "Esfuerzo escolar", "Inteligencia escolar", "Ed media <br> <i>(Ref. Ed Basica)</i>", "Ed tecnica", "Universidad o posgrado", "Ns/Nr", "10 a 25 libros <br> <i>(Ref. Menos de 10)</i>", "26 a 100 libros", "101 a 200 libros", "Más de 200 libros", "Un pc <br> <i>(Ref. Ninguno)</i>", "Dos pc", "Tres o más pc", "Una tablet <br> <i>(Ref. Ninguno)</i>", "Dos tablet", "Tres o mas tablet", "Un celular <br> <i>(Ref. Ninguno)</i>", "Dos celular", "Tres o más celular", "No internet <br> <i>(Ref. Si)</i>", "Ns/Nr internet", "Part. subv <br> <i>(Ref. Municipal)</i>", "Part. priv", "SES Medio bajo <br> <i>(Ref. Bajo)</i>", "SES Medio", "SES Medio alto", "SES Alto", "Simce_Medio <i>(Ref. Bajo)</i>", "Simce_alto"))
```